- name: Try SSH into Server
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SSH_HOST }}  # Check if this name matches your secret
    username: ${{ secrets.SSH_USERNAME }}
    key: ${{ secrets.SSH_KEY }}
    script: |
      echo "Connected!"
